# Generated by Django 3.2.10 on 2022-03-11 12:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Italy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_rip', models.IntegerField(null=True)),
                ('cod_reg', models.IntegerField(null=True)),
                ('cod_prov', models.IntegerField(null=True)),
                ('cod_cm', models.IntegerField(null=True)),
                ('cod_uts', models.IntegerField(null=True)),
                ('pro_com', models.IntegerField(null=True)),
                ('pro_com_t', models.CharField(max_length=6, null=True)),
                ('comune', models.CharField(max_length=100, null=True, verbose_name='comune')),
                ('comune_a', models.CharField(max_length=100, null=True, verbose_name='comune_a')),
                ('cc_uts', models.IntegerField(null=True)),
                ('shape_Leng', models.FloatField(null=True)),
                ('shape_Area', models.FloatField(null=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
