# Generated by Django 3.2.10 on 2022-03-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='area',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='fips',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='iso3',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='pop2005',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='region',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='subregion',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='un',
        ),
        migrations.AddField(
            model_name='worldborder',
            name='cod_cm',
            field=models.IntegerField(null=True, verbose_name='codice cm'),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='cod_pro',
            field=models.IntegerField(null=True, verbose_name='codice provincia'),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='cod_reg',
            field=models.IntegerField(null=True, verbose_name='codice regione'),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='den_cmpro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='flag_cmpro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='provincia',
            field=models.CharField(max_length=50, null=True, verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='shape_Area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='shape_Leng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='sigla',
            field=models.CharField(max_length=3, null=True, verbose_name='siglia'),
        ),
    ]
