# Generated by Django 3.2.10 on 2022-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20220310_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='den_cm',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='den_prov',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='den_uts',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='sigla',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='tipo_uts',
        ),
        migrations.AddField(
            model_name='worldborder',
            name='cc_uts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='comune',
            field=models.CharField(max_length=100, null=True, verbose_name='comune'),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='comune_a',
            field=models.CharField(max_length=100, null=True, verbose_name='comune_a'),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='pro_com',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='pro_com_t',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
